gedknowings:
    urlGed: "%env(urlGed)%"
    urlAlfresco: "%env(urlAlfresco)%"
    organizationContainer: "%env(organizationContainer)%"
    username: "%env(username)%"
    password: "%env(password)%"
